name: Azure Bastion management with Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Create or delete the Azure Bastion resources?"
        required: true
        default: 'create'
        type: choice
        options:
          - 'create'
          - 'delete'

env: # Sets environment variables for Terraform
  TF_WORKDIR: ${{ github.workspace }}/terraform-bastion
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_admin_username: ${{ secrets.BASTION_USERNAME }}
  TF_VAR_admin_password: ${{ secrets.BASTION_PASSWORD }}
  TF_VAR_allowed_ip_address: ${{ secrets.MY_PERSONAL_IP }}

jobs:
  create-or-delete-resources:
    name: Create or Delete resources for VM used as Bastion
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }} # Sets the default working directory for all the steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        # Initializes the bastion-specific backend configuration
        run: terraform init 

      - name: Terraform Plan
        # Runs when 'Resource creation' is the selected action
        if: ${{ inputs.action == 'create' }}
        # Outputs a 'tfplan' file as well as 'tfplan.txt' file (without colors)
        run: terraform plan -out tfplan -no-color | tee tfplan.txt

      - name: Terraform Plan -destroy
        # Runs when 'Resource deletion' is the selected action
        if: ${{ inputs.action == 'delete' }}
        # Outputs a 'tfplan' file as well as 'tfplan.txt' file (without colors)
        run: terraform plan -destroy -out tfplan -no-color | tee tfplan.txt

      - name: Terraform Apply
        run: terraform apply "tfplan" -no-color | tee tfapply.txt

      - name: Save the Terraform Apply Artifact
        # Saves the 'tfapply' file as log if needed for future review/debugging
        uses: actions/upload-artifact@v4
        with:
          name: github-run-id-${{ github.run_id }}-tfapply
          path: ${{ env.TF_WORKDIR }}/tfapply*
          retention-days: 30
          if-no-files-found: error

      - name: Azure Logout and cleanup
        # Runs always - even on previous step fail
        if: ${{ always() }}
        run: |
          az logout
          az cache purge
          az account clear
